### ISSUE TITLE
Respect .gitignore files

### ISSUE THREAD

**Issue by Kyllingene** [rfdzan/dget#1]
This is a really neat project, and I appreciate the use of Levenshtein distance to avoid the complexity of "regular" fuzzy finding. However, it'd be great if it respected .gitignore files, especially when using in a situation like a Cargo project where `/target` has hundreds of files you never want to search. You could perhaps use the [`ignore`](https://crates.io/crates/ignore) crate for this.

**Comment by rfdzan** [comment]
Hi! Thank you for taking your time to check out this project.

This behavior didn't cross my mind and I appreciate the feedback!

Adding this to my to-do list.
